name: 'my_dbt_project'
version: '1.0.0'
config-version: 2


profile: 'dbt_project_profile'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:        
  - "target"
  - "dbt_packages"

models:
  my_dbt_project:
      marts:
          +materialized: table
