dbt_project_profile:
  target: local
  outputs:
    local:
      type: spark
      method: session
      schema: analytics
      host: localhost # not used by session method, but required by dbt-core
